FROM flask_application_stage_1:latest
ARG BUILD_ENV_USERNAME
ARG BUILD_ENV_UID
ARG BUILD_ENV_GID 
ARG BUILD_ENV_GROUPNAME

ENV ENV_USERNAME=$BUILD_ENV_USERNAME
ENV ENV_USER_UID=$BUILD_ENV_UID
ENV ENV_USER_GID=$BUILD_ENV_GID 
ENV ENV_USER_GROUPNAME=$BUILD_ENV_GROUPNAME

## run this twice as sometimes it does not pick up the latest package

RUN /env/bin/pip3 install -i https://test.pypi.org/simple brown-edu-dmtools==0.1.20 ## --upgrade

RUN pip show brown-edu-dmtools

WORKDIR /workdir/flask_application

CMD ["gunicorn"  , "--bind", "0.0.0.0:8010", "wsgi:application" , "--reload"]
